services:
  - type: web
    name: automated-patent-search
    env: node
    buildCommand: yarn install
    startCommand: yarn start
    healthCheckPath: /
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
