services:
  - type: web
    name: automated-patent-search
    env: static
    staticPublishPath: .
    buildCommand: |
      npm install -g http-server
    startCommand: |
      http-server -p $PORT
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
